# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:

services:

  #164.115.33.55
  ca_insurance:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b insurancecore:insurancecorepw -d'
    volumes:
      - ../organizations/fabric-ca/insurance:/etc/hyperledger/fabric-ca-server
    container_name: ca_insurance
    networks:
      - test
    extra_hosts:
      - "peer0.customer.covid-ins.com:164.115.33.56"
      - "peer0.hospital.covid-ins.com:164.115.33.57"

  #164.115.33.55
  ca_hospital:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b hospitalcore:hospitalcorepw -d'
    volumes:
      - ../organizations/fabric-ca/hospital:/etc/hyperledger/fabric-ca-server
    container_name: ca_hospital
    networks:
      - test
    extra_hosts:
      - "peer0.customer.covid-ins.com:164.115.33.56"
      - "peer0.hospital.covid-ins.com:164.115.33.57"

  #164.115.33.55
  ca_customer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-customer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b customercore:customercorepw -d'
    volumes:
      - ../organizations/fabric-ca/customer:/etc/hyperledger/fabric-ca-server
    container_name: ca_customer
    networks:
      - test
    extra_hosts:
      - "peer0.customer.covid-ins.com:164.115.33.56"
      - "peer0.hospital.covid-ins.com:164.115.33.57"

  #164.115.33.55
  ca_orderer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b orderercore:orderercorepw -d'
    volumes:
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - test
    extra_hosts:
      - "peer0.customer.covid-ins.com:164.115.33.56"
      - "peer0.hospital.covid-ins.com:164.115.33.57"
