# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.customer.covid-ins.com:

networks:
  test:

services:
  #164.115.33.56
  peer0.customer.covid-ins.com:
    container_name: peer0.customer.covid-ins.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.customer.covid-ins.com
      - CORE_PEER_ADDRESS=peer0.customer.covid-ins.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.customer.covid-ins.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customer.covid-ins.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customer.covid-ins.com:11051
      - CORE_PEER_LOCALMSPID=CustomerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/customer.covid-ins.com/peers/peer0.customer.covid-ins.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/customer.covid-ins.com/peers/peer0.customer.covid-ins.com/tls:/etc/hyperledger/fabric/tls
        - peer0.customer.covid-ins.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - test
    extra_hosts:
      - "orderer.covid-ins.com:164.115.33.55"
      - "ca_insurance:164.115.33.55"
      - "ca_hospital:164.115.33.55"
      - "ca_customer:164.115.33.55"
      - "ca_orderer:164.115.33.55"
      - "peer0.insurance.covid-ins.com:164.115.33.55"
      - "peer0.hospital.covid-ins.com:164.115.33.57"

